apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
  namespace: sapna-bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
        - name: bms-app
          image: sapna350/bms-app:latest   # replace with your DockerHub image
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          imagePullPolicy: Always
