apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: sapna-bms
spec:
  type: LoadBalancer
  selector:
    app: bms
  ports:
    - port: 80          # Service Port (public-facing)
      targetPort: 3000  # App inside container
