apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
  namespace: sapna-bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
        - name: bms
          image: sapna350/bms-app:latest   # Production Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # Optional: you can add resource limits if needed
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

